# OnePlus 13R specific drivers

obj-$(CONFIG_ONEPLUS_13R) += oneplus_13r.o
obj-$(CONFIG_ONEPLUS_13R_FINGERPRINT) += fingerprint/
obj-$(CONFIG_ONEPLUS_13R_TOUCHSCREEN) += touchscreen/
obj-$(CONFIG_ONEPLUS_13R_DISPLAY) += display/
obj-$(CONFIG_ONEPLUS_13R_CAMERA) += camera/
obj-$(CONFIG_ONEPLUS_13R_BATTERY) += battery/
obj-$(CONFIG_ONEPLUS_13R_CHARGER) += charger/
obj-$(CONFIG_ONEPLUS_13R_VIBRATOR) += vibrator/
obj-$(CONFIG_ONEPLUS_13R_SENSORS) += sensors/
obj-$(CONFIG_ONEPLUS_13R_AUDIO) += audio/
obj-$(CONFIG_ONEPLUS_13R_NFC) += nfc/ 